version: "3.2" # 버전 정보를 작성한다.

services: # 서비스 목록을 정의한다.
        mongo: # 서비스의 이름을 정의한다.
                image : mongo # 해당 서비스에서 사용할 이미지
                restart : always # container를 실행할 때 항상 이미 수행중이라면 재시작
                environment: # 환경 변수를 정의한다
                        MONGO_INITDB_ROOT_USERNAME : root
                        MONGO_INITDB_ROOT_PASSWORD : root12345!
                volumes: 
                        - /c/Users/SAMSUNG/Desktop/hsh/git/Friends-versus/mongodb:/data/db
                container_name: "mongodb_friendversus"
                ports : 
                        - 27017:27017

        mongo-express: 
                image : mongo-express
                restart: always
                container_name : "mongodb_express_friendversus"
                ports:
                    - 8081:8081
                volumes:
                    - /c/Users/SAMSUNG/Desktop/hsh/git/Friends-versus/mongodb:/data/db
                environment: 
                    ME_CONFIG_MONGODB_ADMINUSERNAME : root 
                    ME_CONFIG_MONGODB_ADMINPASSWORD : root12345!
                depends_on: 
                        - mongo

        frontend:
                container_name: myfront
                build:
                        context: Flask_Vue/frontend_vue
                        dockerfile: frontend.Dockerfile
                expose:
                        - 8080
                ports:
                        - 8080:8080
                volumes:
                        - ./Flask_Vue/frontend_vue:/home/data/frontend:cached
                        - /home/data/frontend/node_modules
                environment:
                        - CHOKIDAR_USEPOLLING=true
                

        backend:
                container_name: myback
                build:
                        context: Flask_Vue/backend_flask
                        dockerfile: backend.Dockerfile
                expose:
                        - 5000
                ports:
                        - 5000:5000
                volumes:
                        - ./Flask_Vue/backend_flask:/home/data/backend
                environment:
                        - CHOKIDAR_USEPOLLING=true
                links:
                        - mongo-express
                depends_on: 
                        - frontend